---
- name: Update apt package index
  apt:
    update_cache: yes

- name: Install required packages
  apt:
    name:
      - ca-certificates
      - curl
    state: present

- name: Create /etc/apt/keyrings directory
  file:
    path: /etc/apt/keyrings
    state: directory
    mode: '0755'

- name: Download Docker GPG key
  ansible.builtin.get_url:
    url: https://download.docker.com/linux/ubuntu/gpg
    dest: /etc/apt/keyrings/docker.asc
    mode: '0644'

- name: Add Docker repository
  apt_repository:
    repo: deb [signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/ubuntu focal stable
    state: present

- name: Update apt package index
  apt:
    update_cache: yes

- name: Install Docker packages
  apt:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      # - docker-buildx-plugin
      # - docker-compose-plugin
    state: present

- name: Ensure Docker is started and enabled at boot
  systemd:
    name: docker
    enabled: yes
    state: started

- name: Pull domjudge image
  docker_image:
    name: domjudge/judgehost:latest
    source: pull

# Make directory /opt/scripts
- name: Create /opt/scripts directory
  file:
    path: /opt/scripts
    state: directory
    mode: '0755'

- name: Copy Judgehosts shell script
  copy:
    src: files/scripts/runJudgehosts.sh
    dest: /opt/scripts/runJudgehosts.sh
    mode: '0755'

- name: Copy startAllContainers shell script
  copy:
    src: files/scripts/startAllContainers.sh
    dest: /opt/scripts/startAllContainers.sh
    mode: '0755'

- name: Copy stopAllContainers shell script
  copy:
    src: files/scripts/stopAllContainers.sh
    dest: /opt/scripts/stopAllContainers.sh
    mode: '0755'

- name: Copy removeAllContainers shell script
  copy:
    src: files/scripts/removeAllContainers.sh
    dest: /opt/scripts/removeAllContainers.sh
    mode: '0755'

- name: Copy getPasswords shell script
  copy:
    src: files/scripts/getPasswords.sh
    dest: /opt/scripts/getPasswords.sh
    mode: '0777'

- name: Copy copyFilesToDesktop shell script
  copy:
    src: files/scripts/copyFilesToDesktop.sh
    dest: /opt/copyFilesToDesktop.sh
    mode: '0777'
